### ISSUE TITLE
camelCase rule name not highlighted

### ISSUE THREAD

**Issue by js850** [TheAustinSeven/vscode-pegs#2]
I noticed that rule names with camelCasing are highlighted differently from all lowercase rule names.

![image](https://user-images.githubusercontent.com/1587384/119964891-911a6c80-bfa1-11eb-9ff1-6561efc6fe07.png)

Thanks for creating and publishing this extension, it is very nice :)

**Comment by MixmasterFresh** [comment]
So sorry for not noticing this earlier! Let me take a crack at it.

**Comment by MixmasterFresh** [comment]
Should be fixed in 0.0.6. Feel free to reopen this if it isn't.
