### ISSUE TITLE
"change all occurrences" changes in comments too.

### ISSUE THREAD

**Issue by lagleki** [TheAustinSeven/vscode-pegs#3]
Is it possible to prevent comments from being changed?

**Comment by MixmasterFresh** [comment]
This seems to be how other language extensions work(I tried ruby and java), and I'd be inclined to think it's how language extensions *should* work(if you commented out a line of code, you'd want that line of code to be updated with "change all occurrences" as well). Do you have any example extensions where this is not the case? If you can find one, I would not be opposed to trying to putting this behind a setting so people can turn it on if they want to.
